### PR TITLE
Feature/past

### PR DESCRIPTION
**Pull request by dellamonica**
This PR merges the latest develop branch into feature/past.
I made some changes so that the app runs in my local dev environment (this is blocking automatic merges). They are quite small (docker/django/Dockerfile, requirements/common.txt, voyages/settings.py).

### CODE REVIEW

**Comment by derekjkeller** [comment]
@dellamonica This PR is merging dellamonica:featre/past into rice-crc:develop -- is that intended?

**Comment by dellamonica** [comment]
Hello!

The past feature should now be in good enough shape to be tested in the
Oracle cloud. Do you think we should keep the branch unmerged?

I'm copying John here as well.

Thanks

**Comment by derekjkeller** [comment]
@dellamonica I'd like to keep it separate just until the final transition. We have a bit more testing to do and once it's signed-off, I'll merge develop to main and tag. Once that's done, I'm good with merging feature/past into develop and continuing from there.

@JohnMulligan Feel free to correct me if I'm wrong or you feel different.

**Comment by dellamonica** [comment]
Closing in order to make a PR for the feature/past branch instead.

**Pull request closed without merging**
